#dev
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.162.72:3306/syscentrol?useUnicode=true&characterEncoding=utf-8
    username: root
    password: YUYANG2018